import { AnimatePresence, motion } from "framer-motion";
import Head from "next/head";

const MainLayout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Mascot Awards Film Festival 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <motion.div
          className="content-container"
          initial={{ transform: "translate(-100%, 0)", opacity: 0 }}
          animate={{ transform: "translate(0%, 0)", opacity: 1 }}
          exit={{ transform: "translate(100%, 0)", opacity: 0 }}
        >
          <div className="content">{children}</div>
        </motion.div>
      </main>
    </>
  );
};

export default MainLayout;
